### ISSUE TITLE
Invalid assumption about Tor

### ISSUE THREAD

**Issue by abenmrad** [mattcollier/noxious#16]
First off, I'd like to say that your project is interesting. I was just looking around what you are using node-ths for. :)

However, I read the protocol overview document. And there is a claim about Tor that (rather fortunately) isn't true :

> At the time of this writing, ALL traffic passing over the Tor network is encrypted using the RSA algorithm using a 1024 bit key.

There are indeed 1024bit RSA keypairs used in Tor, but they are only used as identity keys (to prove the identity of each node on the network, as well as hidden services) and, in [previous versions of the protocol (see 5.1.3)](https://gitweb.torproject.org/torspec.git/tree/tor-spec.txt), partly to agree on symmetric keys. And it's the agreed-on symmetric keys that will be used to encrypt trafic data.

There are at least 2 reasons on top of my head on why they fortunately don't use 1024 bits RSA keys to encrypt trafic data :
1. Decryption in RSA takes much more time than encryption, usually. Using symmetric keys to encrypt trafic data while in transit is much faster.
2. But the bigger issue is long term security/forward secrecy. Let's say one day 1024bits RSA is broken (as it's bound to happen a day or an other). If all trafic data was encrypted with such keypairs, and with all the data retention going on on the internet, all Tor trafic can be decrypted in the future. However, the Tor protocol has been designed in a way where a loss of all identity keys doesn't imply that previous trafic can be decrypted. (That concept is called [Forward secrecy](http://en.wikipedia.org/wiki/Forward_secrecy)). Btw, the Tor team are progressively moving away from RSA identity keys in favor of Ed25519 identity keys (a signature scheme based on elliptic curve cryptography). [Here](https://gitweb.torproject.org/torspec.git/tree/proposals/224-rend-spec-ng.txt) is a proposal regarding that change in hidden services.

Just trying to help you out and make things clearer. Tell me what you think :)

**Comment by mattcollier** [comment]
@BatikhSouri, thank you for pointing this out and for providing the reading list!  I have [updated the protocol overview](https://github.com/mattcollier/noxious/commit/ec1383eee8e83c7f98b1a776b2e5224d838073b3).
