### ISSUE TITLE
Uncaught Exception when sending invitations from Windows Build

### ISSUE THREAD

**Issue by diblasio** [mattcollier/noxious#2]
![screen shot 2015-03-26 at 1 53 15 pm](https://cloud.githubusercontent.com/assets/2501539/6854477/929a7fde-d3bf-11e4-94ab-8370eb750bcd.png)

**Comment by mattcollier** [comment]
Uncaught SOCKS exceptions were common to all OS's.  Build 0.0.3 addresses these types of issues.  Closing.
