### ISSUE TITLE
Remove v8 flags

### ISSUE THREAD

**Issue by steelbrain** [mattcollier/noxious#21]
Chrome supports Native ES6 Classes without any kind-of flag (They are stable, Yayyy!), so as of electron v0.25.0 You don't need those v8 flags anymore. You can safely delete that file, and run your code as you normally would.

**Comment by mattcollier** [comment]
That's great news!  Thanks for the update, I'll check it out.

**Comment by diblasio** [comment]
This issue is fixed in 34b8fe5 :+1:
