### ISSUE TITLE
Tor does not always close when noxious is closed on OSX

### ISSUE THREAD

**Issue by diblasio** [mattcollier/noxious#7]
Tor does not always close when noxious is closed on OSX. This results in unexpected behavior when you try to start the application again.

**Comment by diblasio** [comment]
fixed by removing the following lines 

// Quit when all windows are closed.
app.on('window-all-closed', function() {
  if (process.platform != 'darwin')
    app.quit();
});

**Comment by mattcollier** [comment]
See: https://github.com/atom/atom-shell/issues/1357

**Comment by diblasio** [comment]
fixed in version 0.0.6-alpha
