### ISSUE TITLE
Feature Request - Add precompiled binaries for ursa native binary

### ISSUE THREAD

**Issue by diblasio** [mattcollier/noxious#8]
Here's a reference on how this could be done.

https://github.com/mapbox/node-sqlite3/issues/67

**Comment by mattcollier** [comment]
For windows at least, we could install atom-shell and other dependencies with something like NSIS

http://nsis.sourceforge.net/Main_Page

We'd include atom-shell, the openssl binaries (or their installer), and our package built against the included version of atom-shell.

Atom-shell binaries are already being released outside of the NPM system.  https://github.com/atom/atom-shell/releases

**Comment by mattcollier** [comment]
No longer an issue since ursa dependency has been removed.
